- name: Check if node is already joined to cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf
- name: Read join command from file
  ansible.builtin.slurp:
    src: /tmp/kubernetes-join-command
  register: join_command_b64
  delegate_to: localhost
  when: not kubelet_conf.stat.exists
- name: Set join command fact
  ansible.builtin.set_fact:
    join_command: "{{ join_command_b64.content | b64decode | trim }}"
  when: not kubelet_conf.stat.exists
- name: Join worker node to cluster
  ansible.builtin.command: "{{ join_command.split() }}"
  when: not kubelet_conf.stat.exists
  changed_when: true
- name: Wait for kubelet to start
  ansible.builtin.systemd:
    name: kubelet
    state: started
  when: not kubelet_conf.stat.exists
