---
cni_supported_plugins:
  - calico
  - flannel
cni_apply_kubeconfig: /etc/kubernetes/admin.conf
cni_manifest_urls:
  calico: "{{ calico_manifest_url }}"
  flannel: "{{ flannel_manifest_url }}"
cni_daemonsets:
  calico: calico-node
  flannel: kube-flannel-ds
cni_api_wait_retries: 30
cni_api_wait_delay: 10
cni_rollout_timeout: 300s
cni_rollout_retries: 10
cni_rollout_delay: 15
