---
- name: Install and config common package use for k8s
  ansible.builtin.include_tasks: install.yml
  when: common_config_mode == "install"

- name: Remove and drop config use for k8s
  ansible.builtin.include_tasks: remove.yml
  when: common_config_mode == "remove"
