---
- name: Cleanup temporary etcd files on remote nodes
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/etcd.tar.gz
    - "/tmp/etcd-v{{ etcd_version }}-linux-{{ etcd_architecture }}"
  when: not ansible_check_mode
  tags:
    - etcd
    - cleanup

- name: Cleanup temporary etcd files on controller
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/etcd-ca
  delegate_to: localhost
  run_once: true
  become: false
  when: not ansible_check_mode
  tags:
    - etcd
    - cleanup