---
- name: Validate input
  ansible.builtin.import_tasks: validate.yml

- name: Init etcd cluster
  ansible.builtin.import_tasks: init.yml
  when: etcd_mode == "init"

- name: Add etcd node to cluster
  ansible.builtin.import_tasks: add.yml
  when: etcd_mode == "add"

- name: Drop etcd node to cluster
  ansible.builtin.import_tasks: remove.yml
  when: etcd_mode == "drop"

- name: Verify etcd cluster health
  ansible.builtin.import_tasks: health.yml
