---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start etcd
  ansible.builtin.systemd:
    name: etcd
    enabled: true
    state: started

- name: Wait for etcd port to be open
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ etcd_client_port }}"
    delay: 3
    timeout: 60
