---
- name: Check local etcd endpoint health
  ansible.builtin.command: >
    {{ etcd_bin_dir }}/etcdctl endpoint health
    --endpoints=https://{{ ansible_host }}:{{ etcd_client_port }}
    --cacert={{ etcd_cert_dir }}/ca.crt
    --cert={{ etcd_cert_dir }}/healthcheck-client.crt
    --key={{ etcd_cert_dir }}/healthcheck-client.key
  environment:
    ETCDCTL_API: "3"
  register: etcd_local_health
  retries: 12
  delay: 5
  until: etcd_local_health.rc == 0
  changed_when: false

- name: Check full cluster health
  ansible.builtin.command: >
    {{ etcd_bin_dir }}/etcdctl endpoint health
    --endpoints={{ etcd_peers
                   | map(attribute='ip')
                   | map('regex_replace', '^(.*)$', 'https://\1:' + etcd_client_port | string)
                   | join(',') }}
    --cacert={{ etcd_cert_dir }}/ca.crt
    --cert={{ etcd_cert_dir }}/healthcheck-client.crt
    --key={{ etcd_cert_dir }}/healthcheck-client.key
  environment:
    ETCDCTL_API: "3"
  register: etcd_cluster_health
  retries: 6
  delay: 5
  until: etcd_cluster_health.rc == 0
  changed_when: false
  when: inventory_hostname == groups['etcd'][0]

- name: Print cluster health
  ansible.builtin.debug:
    msg: "{{ etcd_cluster_health.stdout_lines }}"
  when: inventory_hostname == groups['etcd'][0]

- name: List etcd cluster members
  ansible.builtin.command: >
    {{ etcd_bin_dir }}/etcdctl member list
    --endpoints=https://{{ ansible_host }}:{{ etcd_client_port }}
    --cacert={{ etcd_cert_dir }}/ca.crt
    --cert={{ etcd_cert_dir }}/healthcheck-client.crt
    --key={{ etcd_cert_dir }}/healthcheck-client.key
    --write-out=table
  environment:
    ETCDCTL_API: "3"
  register: etcd_members
  changed_when: false
  when: inventory_hostname == groups['etcd'][0]

- name: Print cluster members
  ansible.builtin.debug:
    msg: "{{ etcd_members.stdout_lines }}"
  when: inventory_hostname == groups['etcd'][0]
