---
- name: Ensure kubeadm PKI workspace existed on control plane node
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  when: inventory_hostname in cert_control_plane_hosts
  loop:
    - "{{ kubeadm_artifact_dir }}"
    - "{{ cert_kubeadm_cert_dir }}"
    - "{{ cert_kubeadm_cert_dir }}/etcd"

- name: Render kubeadm etcd certificate configuration for control plane nodes
  ansible.builtin.template:
    src: cert-etcd-config.yaml.j2
    dest: "{{ cert_etcd_kubeadm_config_path }}"
    mode: "0600"
  when: inventory_hostname in cert_control_plane_hosts
  vars:
    cert_target_addresses: >-
      {{
        [
          inventory_hostname,
          ansible_host,
          (ip | default(access_ip | default(ansible_host))),
          'localhost',
          '127.0.0.1'
        ] | unique
      }}

- name: Render kubeadm server certificate configuration for control plane nodes
  ansible.builtin.template:
    src: cert-plane-config.yaml.j2
    dest: "{{ cert_control_plane_kubeadm_config_path }}"
    mode: "0600"
  when: inventory_hostname in cert_control_plane_hosts
  vars:
    cert_target_addresses: >-
      {{
        [
          inventory_hostname,
          ansible_host,
          (ip | default(access_ip | default(ansible_host))),
          'localhost',
          '127.0.0.1'
        ] | unique
      }}

- name: Generate etcd server client certificate on each control plane nodes
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - phase
      - certs
      - apiserver-etcd-client
      - --config
      - "{{ cert_control_plane_kubeadm_config_path }}"
  args:
    creates: "{{ cert_kubeadm_cert_dir }}/apiserver-etcd-client.crt"
  when: inventory_hostname in cert_control_plane_hosts

- name: Generate control plane certificate on each control plane nodes
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - phase
      - certs
      - "{{ item.phase }}"
      - --config
      - "{{ cert_control_plane_kubeadm_config_path }}"
  args:
    creates: "{{ cert_kubeadm_cert_dir }}/{{ item.creates }}"
  loop:
    - { phase: apiserver,
        creates: apiserver.crt }
    - { phase: apiserver-kubelet-client,
        creates: apiserver-kubelet-client.crt }
    - { phase: front-proxy-client,
        creates: front-proxy-client.crt }
  when: inventory_hostname in cert_control_plane_hosts
