- name: Add Kubernetes GPG key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
    state: present
- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
    state: present
- name: Update apt package cache
  apt:
    update_cache: true
- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
- name: Start and enable kubelet
  systemd:
    name: kubelet
    enabled: true
    state: started
    daemon_reload: true
