- name: Add Kubernetes GPG key
  ansible.builtin.apt:
    update_cache: false
    state: present
    pkg: apt-transport-https
  register: kubernetes_apt_https
- name: Ensure Kubernetes GPG key is added
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
    state: present
- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
    state: present
    filename: kubernetes
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
- name: Start and enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    state: started
    daemon_reload: true
