---
- name: Validate auth token
  ansible.builtin.assert:
    that:
      - hashivault_admin_token | default('') | length > 0
    fail_msg: "Missing HashiCorp Vault admin token. Set hashivault_admin_token or HASHI_VAULT_TOKEN environment variable."
  no_log: true

- name: Init hashivault config
  delegate_to: localhost
  become: false
  run_once: true
  no_log: true
  when: hashivault_config_mode == "create"
  block:
    - name: Include create tasks
      ansible.builtin.include_tasks: create.yml

- name: Remove hashivault config
  delegate_to: localhost
  become: false
  run_once: true
  no_log: true
  when: hashivault_config_mode == "remove"
  block:
    - name: Include remove tasks
      ansible.builtin.include_tasks: remove.yml
