---
- name: Reload systemd
  listen: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - handlers
    - systemd

- name: Restart etcd
  listen: restart etcd
  ansible.builtin.systemd:
    name: etcd
    state: restarted
    daemon_reload: true
  tags:
    - handlers
    - etcd

- name: Start etcd
  listen: start etcd
  ansible.builtin.systemd:
    name: etcd
    state: started
    enabled: true
    daemon_reload: true
  tags:
    - handlers
    - etcd

- name: Stop etcd
  listen: stop etcd
  ansible.builtin.systemd:
    name: etcd
    state: stopped
  tags:
    - handlers
    - etcd

- name: Reload etcd
  listen: reload etcd
  ansible.builtin.systemd:
    name: etcd
    state: reloaded
  tags:
    - handlers
    - etcd
