---
- name: Validate k8s role input
  ansible.builtin.include_tasks:
    file: validate.yml
    apply:
      tags:
        - validate

- name: Add containerd and kubernetes
  ansible.builtin.include_tasks:
    file: add.yml
    apply:
      tags:
        - add
        - containerd
        - kubernetes
  when: k8s_config_mode | default('install') == "install"

- name: Remove containerd and kubernetes
  ansible.builtin.include_tasks:
    file: remove.yml
    apply:
      tags:
        - remove
        - containerd
        - kubernetes
  when: k8s_config_mode | default('install') == "remove"
