---
- name: Validate k8s role input
  ansible.builtin.include_tasks:
    file: validate.yml
    apply:
      tags:
        - validate

- name: Add containerd and kubernetes
  ansible.builtin.include_tasks:
    file: add.yml
    apply:
      tags:
        - add
        - containerd
        - kubernetes
  when: k8s_mode | default('add') == "add"

- name: Remove containerd and kubernetes
  ansible.builtin.include_tasks:
    file: remove.yml
  when: k8s_mode | default('add') == "remove"
