---
etcd_version: "3.5.9"
etcd_data_dir: "/var/lib/etcd"
etcd_cert_dir: "/etc/etcd/pki"
etcd_config_dir: "/etc/etcd"
etcd_bin_dir: "/usr/local/bin"
etcd_download_dir: "/tmp"

etcd_client_port: 2379
etcd_peer_port: 2380
etcd_cluster_token: "etcd-cluster-k8s"
etcd_initial_cluster_state: "new"
